# Generated by Django 4.2 on 2023-04-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='contect',
            new_name='content',
        ),
    ]
